### ISSUE TITLE
Driver volume on top of a transform

### ISSUE THREAD

**Issue by ungi** [openigtlink/VolumeResliceDriver#3]
The use case is the following: There is an incoming volume node (ultrasound image). In VolumeResliceDriver, I set the ultrasound image itself as driver, so the slice follows the moving image. This has been working fine.
But I created a calibration transform, and dropped the image on top of that in the Data tree. Now, the ultrasound image has been transformed somewhere else, but VulumeResliceDriver still just uses the transform in the volume node (the parent 'calibration' transform is not applied). So the image goes blank in the 3D view.

Would it be possible to use the "to world" transform when an image is the driver, instead of the "to parent" transform?

**Comment by lchauvin** [comment]
We already had this issue before. I thought I fixed it.
Maybe I forgot to commit.

I will check it tomorrow and let you know.

**Comment by ungi** [comment]
I tried it about two weeks ago. Did you fix it since then? I will check again today too.

**Comment by ungi** [comment]
The problem is still there in the latest revision. (Or whatever versions are called in git.) I tested it by uncommenting the random transform ImagerClient2.cxx (from line 160). So I've sent transformed images to Slicer. Then I set up VolumeResliceDriver to drive my Red slice using "ImagerClient", "Position and Orientation" and "Transverse". The slice widget was following the image nicely. But then I created a non identity transform, dropped the ImagerClient volume on top of it, and the problem came out. The image content is transformed, but the slice is not.So I only see an occasional intersection of the image and the slice, as a line.
Thank you for dealing with this.

**Comment by lchauvin** [comment]
I think I fixed this issue on OpenIGTLink in Slicer3 if I remember correctly. I'm gonna fix it, and let you know when updated on git.

**Comment by lchauvin** [comment]
I tried to create a transform and drop it under another transform and it worked. What did you do exactly ? Do you have latest version ?

**Comment by ungi** [comment]
It works with transforms, but it doesn't work with images. When the driver is not a transform node, but the image node itself.

**Comment by lchauvin** [comment]
You're right, when you're reslicing with a node, it's not checking if there is transformation node on top of the image. I briefly tried to fix it, but it didn't work. I will talk to Junichi about it.

**Comment by tokjun** [comment]
It's not as easy as linear transform node. In case of vtkMRMLLinearTransformNode, you can simply call GetMatrixTransformToWorld() to obtain the plane position and orientation in the global coordinate system, but vtkMRMLScalarVolumeNode doesn't seem to have such function. We could implement the following steps in qSlicerReslicePropertyWidgetPrivate::updateSlicerByImageNode()
- Call GetParentTransformNode() of the scalar volume node.
- Get the TransformToWorld of the parent transform node
- Apply the transform to the transform node in the image header (rtimgTransform in the updateSliceByImageNode())

**Comment by ungi** [comment]
Thank you. This sound like a good solution. Could somebody please commit it?

**Comment by tokjun** [comment]
I implemented the suggested code and uploaded to the server. However, this does not detect an update of parent transforms. Does this work for you?

**Comment by ungi** [comment]
Thank you so much. It works for me. The calibration transform I apply on the image is constant.

**Comment by tokjun** [comment]
I realized that it was easy to detect the parent transform update. Now the module can drive the replacing plane by image transform and parent transform node. The code is available since commit a6728800afe732c09d320d1e96015cb5286d68b4

**Comment by ungi** [comment]
Indeed, it looks much better with this update.
